# name: Playwright Tests
# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#       - name: Install dependencies
#         run: npm install -g yarn && yarn
#       - name: Install Playwright Browsers
#         run: yarn playwright install chromium
#       - name: Run Playwright tests
#         run: yarn e2e:prepare && yarn && npx playwright test && yarn e2e:cleanup
#       - uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30

name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Register User
        run: yarn e2e:prepare
      - name: Upload Email Address Artifact
        uses: actions/upload-artifact@v4
        with:
          name: email-address
          path: e2e/setup/temp.json
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-stage1
          path: playwright-report/
          retention-days: 30

  stage2:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Download Email Address Artifact in Stage 2
        uses: actions/download-artifact@v4
        with:
          name: email-address
          path: e2e/setup/
      - name: Run Tests
        run: yarn test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-stage2
          path: playwright-report/
          retention-days: 30

  stage3:
    runs-on: ubuntu-latest
    needs: stage2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Download Email Address Artifact in Stage 2
        uses: actions/download-artifact@v4
        with:
          name: email-address
          path: e2e/setup/
      - name: Cleanup Stage
        run: yarn e2e:cleanup
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-stage3
          path: playwright-report/
          retention-days: 30

  deploy_reports:
    runs-on: ubuntu-latest
    needs: stage3
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
      - name: Deploy Playwright Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          folder: playwright-report
